Do not use nested list initialization
Some compilers handle this differently, wrapping the list in
another list. This causes runtime failures, such as:

    RuntimeError: get_transactions exception:[json.exception.type_error.305] cannot use operator[] with a string argument with array

as we expect a list of maps but we have a list containing a list of
maps.