[FIX] Fixed reference to deprecated function PyEval_CallObject
PyEval_CallObject() has been deprecated since Python 3.9 (https://docs.python.org/3.13/whatsnew/3.9.html), and thus building the Python wrapper fails with the following errors when compiling with clang:

swig_green_gdk_wrap.c:3359:15: error: call to undeclared function 'PyEval_CallObject'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3359 |     handler = PyEval_CallObject(handler_ref, NULL);
      |               ^
swig_green_gdk_wrap.c:3359:13: error: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
 3359 |     handler = PyEval_CallObject(handler_ref, NULL);
      |             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
swig_green_gdk_wrap.c:3369:13: error: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
 3369 |         ret = PyEval_CallObject(handler, args);
      |             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 errors generated.

The current Python specs recommend to use PyObject_CallObject() instead of PyEval_CallObject(). This PR changes the swig_green_gdk.i file to reflect these recommendations.